### ISSUE TITLE
Component Tree

### ISSUE THREAD

**Issue by CharlesDLandau** [codefordc/rfj_expungement#15]
We need a component tree!

- [x] Top level data view encoding top level form logic (e.g. client name, date of case) #19 
- [x] Row component for the table using indicator and content component #20 
- [x] Indicator component for the row #21 
- [x] Charge eligibility view #24
- [x] Persistent nav buttons #25
- [x] Form components typical to a webform #23
- [ ] Rich text editor #26

**Comment by beckybell13** [comment]
Will work on the Row component! (#20 )

**Comment by dhruvturakhia** [comment]
Working on the Persistent Nav Buttons 😄  (#25 )

**Comment by froi** [comment]
Hello everybody.

The PR associated with issue #26 has been merged. Should we close #26 and complete the check boxes in this issue?

CC: @CharlesDLandau

**Comment by cmazzullo** [comment]
Just bumping Froi's suggestion - this issue should be closed.

**Comment by CharlesDLandau** [comment]
Apologies for the slow turn on this I don't rightly know how I let it fall through the cracks.
